### ISSUE TITLE
413 Request Entity Too Large when attempting to send request to Vault

### ISSUE THREAD

**Issue by Thundercraft5** [coddingtonbear/obsidian-local-rest-api#82] opened 2023-11-28 08:34 UTC
I attempted to save a rather long article [about the AI executive order from october](https://www.whitehouse.gov/briefing-room/presidential-actions/2023/10/30/executive-order-on-the-safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence/), but I encountered an HTTP 413 from the local webserver.

![brave_qgvcKAspN1](https://github.com/coddingtonbear/obsidian-local-rest-api/assets/69543685/77c2eaef-43a7-417d-bef5-625c02d30e92)

**Comment by coddingtonbear** [comment] 2023-11-28 11:53
Duplicate of #73

**Closed** 2023-11-28 11:53 UTC
