### ISSUE TITLE
Cannot install with error : failed to install module 

### ISSUE THREAD

**Issue by sangorys** [coddingtonbear/obsidian-local-rest-api#102] opened 2024-01-23 08:59 UTC
What I did : 
- Click on Install to install the module

What happens : 
- Error message : failed to install module 
- The module is not installed

Environment : 
- Windows 10
- Obsidian 1.5.3

Please help (and help me to find the debug info also).

**Comment by owrede** [comment] 2024-01-23 13:19
I think that is the same issue with the current 2.0.5 release like this issue here: https://github.com/coddingtonbear/obsidian-local-rest-api/issues/101

**Comment by Cossackx** [comment] 2024-01-25 03:18
same

**Comment by dsenften** [comment] 2024-01-25 10:02
I have the same problem on my Mac.

- Obsidian, v1.5.3
- macOS v14.2.1 (M1)

**Comment by smellsworth** [comment] 2024-01-25 13:59
Samesies.

- Obsidian: Version 1.5.3 (Installer 1.4.14)
- macOS: 14.2.1 (M1)

Lastly, this plugin is great. Thank you for the work you are doing.

**Comment by dsamersoff** [comment] 2024-01-25 19:13
Same problem for me. 

404 error in console, so I suspect that it's mismatch between 2.0.4 tag and 2.0.3 package name.

**Comment by owrede** [comment] 2024-01-25 22:13
Seems there is a build error that prevented that the needed files have been deployed:
https://github.com/coddingtonbear/obsidian-local-rest-api/actions/runs/7601968816/job/20701963503

**Comment by cgcomer** [comment] 2024-01-27 21:13
This is still an issue for me. 
Win 11 Pro 23H2 (Build 22631.3085)
Obsidian 1.5.3

**Comment by MatiasVerdier** [comment] 2024-01-28 08:45
I've posted a temporary solution here https://github.com/coddingtonbear/obsidian-local-rest-api/issues/101#issuecomment-1913517748

**Comment by coddingtonbear** [comment] 2024-01-30 02:51
This is a duplicate of #101

**Closed by coddingtonbear** 2024-01-30 02:51 UTC
